"""empty message

Revision ID: dfb7dbd963b8
Revises: 
Create Date: 2019-02-03 10:13:39.095919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb7dbd963b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('street1', sa.String(length=64), nullable=True),
    sa.Column('street2', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=6), nullable=True),
    sa.Column('zip', sa.String(length=16), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('last_purchase', sa.DateTime(), nullable=True),
    sa.Column('reward_points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_city'), 'customer', ['city'], unique=False)
    op.create_index(op.f('ix_customer_country'), 'customer', ['country'], unique=False)
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=True)
    op.create_index(op.f('ix_customer_first_name'), 'customer', ['first_name'], unique=False)
    op.create_index(op.f('ix_customer_last_name'), 'customer', ['last_name'], unique=False)
    op.create_index(op.f('ix_customer_state'), 'customer', ['state'], unique=False)
    op.create_index(op.f('ix_customer_street1'), 'customer', ['street1'], unique=False)
    op.create_index(op.f('ix_customer_street2'), 'customer', ['street2'], unique=False)
    op.create_index(op.f('ix_customer_zip'), 'customer', ['zip'], unique=False)
    op.create_table('item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('cost', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('price', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=False),
    sa.Column('item_number', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Float(precision=10, asdecimal=3), nullable=True),
    sa.Column('last_sold', sa.DateTime(), nullable=True),
    sa.Column('serial_number', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_description'), 'item', ['description'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('tax_rate', sa.Float(precision=2, asdecimal=2), nullable=True),
    sa.Column('tax', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('subtotal', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('total', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_purchase',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'purchase_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_purchase')
    op.drop_table('purchase')
    op.drop_table('user')
    op.drop_index(op.f('ix_item_description'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_customer_zip'), table_name='customer')
    op.drop_index(op.f('ix_customer_street2'), table_name='customer')
    op.drop_index(op.f('ix_customer_street1'), table_name='customer')
    op.drop_index(op.f('ix_customer_state'), table_name='customer')
    op.drop_index(op.f('ix_customer_last_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_first_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.drop_index(op.f('ix_customer_country'), table_name='customer')
    op.drop_index(op.f('ix_customer_city'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
