"""rename invetory column

Revision ID: 6168e5ffb244
Revises: f4167394ba5d
Create Date: 2019-01-21 15:13:00.720256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6168e5ffb244'
down_revision = 'f4167394ba5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('quantity', sa.Float(precision=10, asdecimal=3), nullable=True))
    op.drop_column('item', 'inventory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('inventory', sa.FLOAT(), nullable=True))
    op.drop_column('item', 'quantity')
    # ### end Alembic commands ###
