"""add User, Purchase, and Item

Revision ID: d8491d765e07
Revises: 0cc82c42cea5
Create Date: 2019-01-19 16:19:47.365100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8491d765e07'
down_revision = '0cc82c42cea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('street1', sa.String(length=64), nullable=True),
    sa.Column('street2', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=6), nullable=True),
    sa.Column('zip', sa.String(length=16), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('last_purchase', sa.DateTime(), nullable=True),
    sa.Column('reward_points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_city'), 'customer', ['city'], unique=False)
    op.create_index(op.f('ix_customer_country'), 'customer', ['country'], unique=False)
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=True)
    op.create_index(op.f('ix_customer_first_name'), 'customer', ['first_name'], unique=False)
    op.create_index(op.f('ix_customer_last_name'), 'customer', ['last_name'], unique=False)
    op.create_index(op.f('ix_customer_state'), 'customer', ['state'], unique=False)
    op.create_index(op.f('ix_customer_street1'), 'customer', ['street1'], unique=False)
    op.create_index(op.f('ix_customer_street2'), 'customer', ['street2'], unique=False)
    op.create_index(op.f('ix_customer_zip'), 'customer', ['zip'], unique=False)
    op.create_table('item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('cost', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('price', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=False),
    sa.Column('inventory', sa.Float(precision=10, asdecimal=3), nullable=True),
    sa.Column('last_sold', sa.DateTime(), nullable=True),
    sa.Column('serial_number', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_description'), 'item', ['description'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('tax_rate', sa.Float(precision=2, asdecimal=2), nullable=True),
    sa.Column('tax', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('subtotal', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('total', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_customers_city', table_name='customers')
    op.drop_index('ix_customers_country', table_name='customers')
    op.drop_index('ix_customers_email', table_name='customers')
    op.drop_index('ix_customers_first_name', table_name='customers')
    op.drop_index('ix_customers_last_name', table_name='customers')
    op.drop_index('ix_customers_state', table_name='customers')
    op.drop_index('ix_customers_street1', table_name='customers')
    op.drop_index('ix_customers_street2', table_name='customers')
    op.drop_index('ix_customers_zip', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('birthday', sa.DATETIME(), nullable=True),
    sa.Column('street1', sa.VARCHAR(length=64), nullable=True),
    sa.Column('street2', sa.VARCHAR(length=64), nullable=True),
    sa.Column('city', sa.VARCHAR(length=64), nullable=True),
    sa.Column('state', sa.VARCHAR(length=6), nullable=True),
    sa.Column('zip', sa.VARCHAR(length=16), nullable=True),
    sa.Column('country', sa.VARCHAR(length=64), nullable=True),
    sa.Column('last_purchase', sa.DATETIME(), nullable=True),
    sa.Column('reward_points', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index('ix_customers_zip', 'customers', ['zip'], unique=False)
    op.create_index('ix_customers_street2', 'customers', ['street2'], unique=False)
    op.create_index('ix_customers_street1', 'customers', ['street1'], unique=False)
    op.create_index('ix_customers_state', 'customers', ['state'], unique=False)
    op.create_index('ix_customers_last_name', 'customers', ['last_name'], unique=False)
    op.create_index('ix_customers_first_name', 'customers', ['first_name'], unique=False)
    op.create_index('ix_customers_email', 'customers', ['email'], unique=1)
    op.create_index('ix_customers_country', 'customers', ['country'], unique=False)
    op.create_index('ix_customers_city', 'customers', ['city'], unique=False)
    op.drop_table('purchase')
    op.drop_table('user')
    op.drop_index(op.f('ix_item_description'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_customer_zip'), table_name='customer')
    op.drop_index(op.f('ix_customer_street2'), table_name='customer')
    op.drop_index(op.f('ix_customer_street1'), table_name='customer')
    op.drop_index(op.f('ix_customer_state'), table_name='customer')
    op.drop_index(op.f('ix_customer_last_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_first_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.drop_index(op.f('ix_customer_country'), table_name='customer')
    op.drop_index(op.f('ix_customer_city'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
