"""add item number to Item

Revision ID: f4167394ba5d
Revises: 4c9fec71ab0a
Create Date: 2019-01-21 15:07:59.072366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4167394ba5d'
down_revision = '4c9fec71ab0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('item_number', sa.String(length=128)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'item_number')
    # ### end Alembic commands ###
